### ISSUE TITLE
No Force sensor dashboard

### ISSUE THREAD

**Issue by haniehes** [icub-tech-iit/ft-sensors-simulink#8]
Hi, I have just downloaded this package to use it for FT45_M4 iiT sensor, but I noticed differences in FT_CAN_messages.slx and your readme file. 
In the .slx file:
1) the general management window doesn't have "set can datarate" tab.
2) **FT management** window and **send FT Msg** doesn't exist!

**Comment by mfussi66** [comment]
Hi @haniehes, 
Thanks for raising this issue! I removed the dashboard elements you mentioned because of internal usage purposes, but you rightly point out that it does not match the readme, so I'll add all that stuff back. 
While I do that, you can roll back to a previous version of the model by checking out the commit https://github.com/icub-tech-iit/ft-sensors-simulink/commit/11fb0835bb68722719b334ba9e1abafe53dbd756 with:
```
git checkout 11fb083
```
That version should match the readme.

**Comment by mfussi66** [comment]
Hi @haniehes , I created a PR to roll back the changes https://github.com/icub-tech-iit/ft-sensors-simulink/pull/9
